### ISSUE TITLE
请问这个能用来在web端播放rtsp视频流吗？后端还要怎么配置？

### ISSUE THREAD

**Issue by freehzw** [PittYao/VideoPlayer#1]
请问这个能用来在web端播放rtsp视频流吗？后端还要怎么配置？

**Comment by PittYao** [comment]
> 请问这个能用来在web端播放rtsp视频流吗？后端还要怎么配置？

要配合后端的程序才能播放

**Comment by bk201lucifer** [comment]
有后端吗

**Comment by jambestwick** [comment]
具体有文档吗，大神

**Comment by PittYao** [comment]
> 具体有文档吗，大神



> 有后端吗

仓库 videoPlayer_backend

**Comment by PittYao** [comment]
> 具体有文档吗，大神

vue文档见readme 后端仓库 videoPlayer_backend

**Comment by jambestwick** [comment]
ok,有时间看看
